In [1]:
#encoding
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')

df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
y, class_names = pd.factorize(df.species,sort=True)

In [6]:
print(pd.unique(y))
y

[0 1 2]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [7]:
class_names

Index(['setosa', 'versicolor', 'virginica'], dtype='object')

In [10]:
from tensorflow.keras.utils import to_categorical

to_categorical(1, 3).astype('int')

array([0, 1, 0])

In [23]:
categorises , ids = np.unique(df.species,return_inverse=True)

In [21]:
ids ,categorises =  pd.factorize(df.species,sort=True)

In [24]:
ids

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [25]:
df.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [33]:
from tensorflow.keras.utils import to_categorical

def one_hot_encode(arr):
    categories,ids = np.unique(arr,return_inverse=1)
    return to_categorical(ids,len(categories))

y_1h = one_hot_encode(df.species).astype('int')

y_1h[:5]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [34]:
df.iloc[14].species

'setosa'

In [35]:
y[14]

0

In [39]:
print('  data      Label-Encoded   one-hot')
print('-----------------------------------')
for k in [98,5,6,7,8,96,69]:
     print(f'{df.loc[k].species:17} {y[k]:<8}  {y_1h[k]}')

  data      Label-Encoded   one-hot
-----------------------------------
versicolor        1         [0 1 0]
setosa            0         [1 0 0]
setosa            0         [1 0 0]
setosa            0         [1 0 0]
setosa            0         [1 0 0]
versicolor        1         [0 1 0]
versicolor        1         [0 1 0]


In [40]:
#padas : get dummies
y[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [48]:
y_hgd = pd.get_dummies(y)
print(type(y_hgd))
yp =y_hgd.to_numpy()
yp[:5]

<class 'pandas.core.frame.DataFrame'>


array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=uint8)

In [49]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()

y2 = df.species.to_numpy()
y2[:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype=object)

In [52]:
y2=y2.reshape(-1,1)
y2[:6]

array([['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa']], dtype=object)

In [56]:
y_1hsk = enc.fit_transform(y2).toarray().astype('int')

y_1hsk[:6]




array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])